"use client";

// Wrapper untuk lucide-react.
// lucide-react mengakses react.createContext di module scope sehingga
// tidak bisa dievaluasi di React Server Components. Dengan membungkus
// di file "use client", ikon hanya dimuat di sisi client.
export {
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  BarChart3,
  Bell,
  Building2,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  Clock3,
  Eye,
  Filter,
  Inbox,
  LayoutDashboard,
  Lightbulb,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Package,
  Pencil,
  Phone,
  Plus,
  Receipt,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Sliders,
  Sparkles,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  User,
  UserCircle2,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";